name: Run tests

on:
  push:
    branches: [ main ]

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: 'root'
          MARIADB_DATABASE: 'test_load_data'

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          USING_DOCKER: true
        run: ./vendor/bin/phpunit --stop-on-failure
      